[package]
name = "dir-2-html"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { version = "0.4.21", features = ["max_level_trace"] }
simple_logger = "5.0.0"
